Sync keyscan with host script. Fixes #5.
Sync usage of openssl.
Add basic errors handling and usage.

diff --git a/ssh-keyscan2sshfp b/ssh-keyscan2sshfp
--- a/ssh-keyscan2sshfp
+++ b/ssh-keyscan2sshfp
@@ -4,12 +4,26 @@
 # author: Danny Fullerton - Mantor Organization www.mantor.org
 # license: public domain
 
-echo "####################################################"
-echo "# Should not be used unless you can really trust your"
-echo "# network... but who can?!?"
-echo "####################################################"
+echo "############################################"
+echo "# Should not be used unless you can really #"
+echo "# trust your network... but who can?!?     #"
+echo "############################################"
+echo ""
 
-sigs=`ssh-keyscan -t ecdsa,dsa,rsa,ed25519 $* 2> /dev/null`
+if [ $# -lt 1 ] || [ "$1" = "-h" ]; then
+  echo "Usage: $0 <fully qualified domain names>" >&2
+  exit 1
+fi
+fqdn=$1
+ 
+sigs=`ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $* 2> /dev/null`
+if [ $? != 0 ]; then
+  echo "Error: ssh-keyscan failed. Check the hostnames." >&2
+  exit 1
+fi
+
+hash1='sha1'
+hash2='sha256' 
 
 while IFS= read -r line; do
   echo $line | grep -E '^#' > /dev/null
@@ -17,26 +31,23 @@ while IFS= read -r line; do
     continue
   fi
 
-  host=`echo -n $line | awk '{print $1}'`
-  algo=`echo -n $line | awk '{print $2}'`
-  sig_sha1=`echo -n $line | awk '{print $3}' | openssl base64 -d -A | openssl dgst -sha1 -r | awk '{print $1}' | tr '[a-z]' '[A-Z]'`
-  sig_sha2=`echo -n $line | awk '{print $3}' | openssl base64 -d -A | openssl dgst -sha256 -r | awk '{print $1}' | tr '[a-z]' '[A-Z]'`
-
-  case "$algo" in
+  fqdn=`echo -n $line | awk '{print $1}'`
+  case `echo -n $line | awk '{print $2}'` in
     'ssh-rsa')
-      algo="1"
-      ;;
+      algo="1" ;;
     'ssh-dss')
-      algo="2"
-      ;;
+      algo="2" ;;
     'ecdsa-sha2-nistp256')
-      algo="3"
-      ;;
+      algo="3" ;;
     'ssh-ed25519')
-      algo="4"
-      ;;
+      algo="4" ;;
   esac
 
-  echo "${host}. IN SSHFP $algo 1 $sig_sha1"
-  echo "${host}. IN SSHFP $algo 2 $sig_sha2"
+  for j in `seq 1 2` # hash
+  do
+    eval "h=\${hash${j}}"
+    sshfp=`echo -n $line | awk '{print $3}' | openssl base64 -d -A | openssl dgst -${h} | sed 's/^.* //' | awk '{print $1}' | tr '[a-z]' '[A-Z]'`
+    echo "${fqdn}. IN SSHFP $algo ${j} ${sshfp}"
+  done
+
 done <<< "$sigs"
